redhat-openstack/infrared

.travis.yml, cli/conf.py, cli/utils.py
This patch adds an installation of 'pytest-random' PyPi package which
adds the ability to run the unittests in random order.
when running with '-v/--verbose' flag, the seed will be printed to
stdout to allow running in same order if want (--random-seed=xxxxx must
come with --random)
resolves #9
=> Adds randomization in testint order

playbooks/installer/ospd/overcloud/templates/overcloud_deploy.sh.j2, settings/installer/ospd/network/isolation/protocol/ipv4.yml, settings/installer/ospd/network/isolation/protocol/ipv6.yml
This patch fixes the issue where the vlan was not configured properly
on a three-nic-isolation deployment.
=> [RHOSINFRA-65] - Vlan fix

cli/conf.py
=> [RHOSINFRA-41] Use default configurations if infrared.cfg doesn't exist

cli/spec.py, tests/test_spec.py
Added check that all the required arguments are set. 
We can check for that once all the arguments are loaded from cli, ini files and environment. So check was added to the end of parse_spec method. 
@yfried-redhat please review and let me know about any suggestions.
=> [RHOSINFRA-91] Add check for required arguments

playbooks/installer/ospd/overcloud/run.yml, roles/ospd/overcloud/storage/netapp/tasks/main.yml, roles/ospd/overcloud/storage/netapp/templates/netapp.yml.j2, settings/installer/ospd/storage/ceph.yml, settings/installer/ospd/storage/netapp.yml, settings/installer/ospd/storage/netapp/protocol/iscsi.yml, settings/installer/ospd/storage/netapp/protocol/nfs.yml
Yogev Rabl confirmed that the iscsi protocol works fine with a workaround and that the nfs doesn't work atm - he's working to find the reason for that
(https://bugzilla.redhat.com/show_bug.cgi?id=1321453)
Per @tkammer request, it is possible to review this PR and merged it if it passed the review and the gate, in order to create 2 jobs for the NetApp backend, one for iscsi and one for nfs.
Resolves RHOSINFRA-93
Resolves RHOSINFRA-97
=> [RHOSINFRA-98] Add support for NetApp storage backend

cli/spec.py, cli/utils.py, tests/test_spec.py
Now we can use choices for Value arguments. 
@yfried-redhat @aopincar, please review.
=> [RHOSINFRA-96] Fix 'choices' issue in spec parser

settings/tester/tempest/tests/sanity.yml
This is a temporary solution to nightly jobs who doesn't need to ran the whole
tempest, only a basic set of jobs to ensure that the basic tests were passing.
=> Adding sanity option to tempest-tests

library/os_floating_ip.py, playbooks/provisioner/openstack/cleanup.yaml, playbooks/provisioner/openstack/main.yaml, plugins/filters/add_prefix.py, requirements.txt, roles/openstack/neutron/defaults/main.yml, roles/openstack/neutron/tasks/cleanup.yml, roles/openstack/neutron/tasks/main.yml, roles/openstack/neutron/tasks/setup.yml, roles/openstack/nova/defaults/main.yml, roles/openstack/nova/tasks/cleanup.yml, roles/openstack/nova/tasks/cleanup_nodes.yml, roles/openstack/nova/tasks/main.yml, roles/openstack/nova/tasks/setup.yml, roles/openstack/nova/tasks/setup_nodes.yml, settings/provisioner/openstack/neutron/default.yml, settings/provisioner/openstack/openstack.spec, settings/provisioner/openstack/openstack.yml, settings/provisioner/topology/ceph.yaml, settings/provisioner/topology/compute.yaml, settings/provisioner/topology/controller.yaml, settings/provisioner/topology/undercloud.yaml
Added OpenStack provisioner.
It is used for creating and/or removing resources on OpenStack clouds.
Includes:
* provision networks
- Allows to specify if network is shared
- Allows to specify timeout for network
* provisiom subnets
- Allows to specify cidr, dns servers, allocation pool
and whether DHCP should be enabled
* provision routers
- Allows to attach network interfaces
- Allows to specify default gateway
* provision instances
- Allows to specify config_drive, nics, image and flavor
* provision flavors
- Allows to specify ram, disk and vcpus
* provision floating IPs
- Allows to reuse existing floating IPs
- Allows to specify fixed IP address
The style is based on:
* 4 spaces
* module variables are sorted alphabetically
* blank line after each task
=>  RHOSINFRA-52 Add 'openstack' provisioner

settings/tester/tempest/setup/git.yml
Tempest upstream requires testtools>= 1.4.0 while we were still using
testtools 0.9. This makes some tests fails in assertRaisesRegex since
testtools 0.9 doesn't have this method, only the assertRaisesRegexp that
were deprecated.
=> Updating testtools dependences to match tempest upstream

cli/spec.py, cli/utils.py, settings/installer/ospd/ospd.spec, settings/provisioner/openstack/openstack.spec, settings/provisioner/virsh/virsh.spec, tests/test_spec.py
Print all the available options for YamlFile arguments into the help message. 
@yfried-redhat @tkammer please review. 
Help output example: 
```
Undercloud:
--undercloud-config UNDERCLOUD-CONFIG
The undercloud config details
Default value: default.yml
Available files: { default.yml }
Overcloud:
--overcloud-ssl OVERCLOUD-SSL
Specifies whether ths SSL should be used for overcloud
Default value: no
Overcloud storage:
--storage STORAGE     The overcloud storage type
Default value: ceph.yml
Available files: { ceph.yml, netapp-iscsi.yml, netapp-nfs.yml, ceph-external.yml }
```
=> [RHOSINFRA-134] Print available yaml files to the help message

cli/spec.py, cli/utils.py, settings/provisioner/virsh/virsh.spec, tests/test_spec.py
Display warnings when we use defaults values from spec file. 
Examples: 
```
(venv)➜  InfraRed git:(RHOSINFRA-144-part2) ✗ ir-installer ospd
WARNING Argument 'network-backend' was not supplied. Using: 'vxlan' as default.
WARNING Argument 'firewall' was not supplied. Using: 'default.yml' as default.
WARNING Argument 'product-build' was not supplied. Using: 'latest' as default.
WARNING Argument 'undercloud-config' was not supplied. Using: 'default.yml' as default.
WARNING Argument 'user-password' was not supplied. Using: 'stack' as default.
WARNING Argument 'user-name' was not supplied. Using: 'stack' as default.
WARNING Argument 'network-protocol' was not supplied. Using: 'ipv4' as default.
WARNING Argument 'overcloud-ssl' was not supplied. Using: 'no' as default.
WARNING Argument …
```
=> [RHOSINFRA-144] Ux improvements for confgi file and defaults values

roles/openstack/nova/defaults/main.yml
It would be more accurate to point "m1.large" by name
rather than guessing it's id number 4.
=> Change default flavor from id to name

playbooks/provisioner/openstack/main.yml, roles/openstack/nova/tasks/setup_nodes.yml
With OpenStack provisioner hosts from same group get the same IP at the
'Add created servers to inventory' task.
=> [RHOSINFRA-150] Fixes wrong IP for same group hosts - openstack provisioner

requirements.txt
@yfried-redhat, can you please review?
=> [RHOSINFRA-154] Fix Babel in requirements.

README.rst, local_hosts, playbooks/cleanup.yml, templates/inventory.j2
Use default python interpreter on localhost.
Ansible will use the system python interpreter by default, but on
localhost, user might be using virtualenv.
Write this to inventory files as well.
=> Virtualenv support

settings/provisioner/topology/tester.yml
Before this change, the only node in tester group
was undercloud.
There is a use case ( component testing ) for testing
on one provisioned node and this is way 'tester' node
was added to the topology.
=> Add tester

roles/openstack/neutron/defaults/main.yml, roles/openstack/neutron/tasks/setup.yml, settings/provisioner/openstack/openstack.spec
This allows users to specify their own DNS.
=> Add 'dns' argument to OpenStack provisioner

playbooks/provisioner/beaker/main.yml
There was redundant ansible_ssh_password parameter - this one is not
known by ansible.
See: http://docs.ansible.com/ansible/intro_inventory.html
=> Small cleanup of beaker add_host module

requirements.txt
```
$ ir-provisioner -d -vvvv openstack -o provision.yml --image=rhel-guest-image-7.2-20151102.0 --cloud rhos-qe-ci --prefix=gate-infrared-246-br-RHOSINFRA-107-pr-205- --nodes=1_controller,2_compute '--key-file=~/.ssh/rhos-jenkins/id_rsa' --key-name=rhos-jenkins
Traceback (most recent call last):
File "/home/rhos-ci/jenkins/shiningpanda/jobs/ef9c0e94/virtualenvs/d41d8cd9/bin/ir-provisioner", line 5, in <module>
from pkg_resources import load_entry_point
File "/home/rhos-ci/jenkins/shiningpanda/jobs/ef9c0e94/virtualenvs/d41d8cd9/lib/python2.7/site-packages/pkg_resources.py", line 2829, in <module>
working_set = WorkingSet._build_master()
File "/home/rhos-ci/jenkins/shiningpanda/jobs/ef9c0e94/virtualenvs/d41d8cd9/lib/python2.7/site-packages/pkg_resources.py", line 451, in _build_master …
```
=> Update setuptools requirements

cli/exceptions.py, cli/spec.py
Message for wrong topology format is now more informative and includes an example of right usage.
Improved the topology format validation using regex.
Resolves RHOSINFRA-107
=> [RHOSINFRA-107] Adds more informative message for wrong topology

playbooks/provisioner/beaker/main.yml, roles/provisioner/virsh/tasks/main.yml, templates/inventory.j2
Replaced it with 'ansible_ssh_pass'.
Pull request #194 broke the beaker provisioner module, because it
removed the use in 'ansible_ssh_password' from the beaker playbook
only, but there is a use of it in the 'inventory.j2' template.
=> Removes the use in 'ansible_ssh_password'

cli/spec.py
Help screen displays all parameters as optionals.
This fixes skip the preprocess arguments stage if '-h'/'--help' is
given.
Resolves RHOSINFRA-129
=> [RHOSINFRA-129] Fixes all parameters are optionals in help screen

playbooks/provisioner/beaker/main.yml
Adds a task to the Beaker main playbook which removes the fingerprint
of host provisioned with Beaker from the known_hosts file
=> Removes fingerprint of host from known_host

docs/source/setup.rst, setup.py
File modules (copy/file/template) require selinux binding, which isn't
provided in pypy and thus unsupported by virtualenv.
Get it from system during installation.
=> Get selinux binding during installation

roles/installer/ospd/images/defaults/main.yml, roles/installer/ospd/images/tasks/rpm.yml, settings/installer/ospd/ospd.spec
Started in OSPD 9 (and backported to 8), overcloud images are packaged
with product RPM.
Also requires some casting of arguments from int values to string.
=> [OSPD] Adds support to fetch images from RPM

cli/utils.py
```yaml
dict:
k1:
k2: "string"
```
dict_insert(dict, some_dict_val, k1.k2)
Trying to insert a dict value to a place where none-dict value exists
would invoke dict merge with (none-dict, dict) input resulting in error.
Solution: only invoke dict_merge if both items are dict. otherwise,
overwrite none-dict value.
=> HOTFIX dict insert

playbooks/collect-logs.yml
This is necessary in case we are building images and since these images
have usually more than 10GB, when we collect the logs, the tarball
became huge unecessary.
=> Avoid files bigger than 1GB be added in the collect logs tarball

playbooks/installer/ospd/virthost.yml, roles/installer/ospd/undercloud/tasks/setup.yml
Rhos-release tool is not maintaining dependencies
between ospd and core versions properly when "latest"
is not specified. Therefore ability to specify certain
version numbers must be working (until this broken) and called
in specific order. First, we need to call rhos-release with
{{ installer.product.version }}-director and version number
and then {{ installer.product.core.version }} with different
specific core version number. Otherwise, rhos-release end up
in creating repositories with links to non-existing repos
and deployment will fail.
This fixes issues 171 and 256.
=> Fix broken handling of rhos-release

playbooks/collect-logs.yml
As per psedlak request, the compression level for .xz is bigger than
.gz making the artifacts smaller.
=> RHOSINFRA-118 - Changing compression from .tar.gz to .tar.xz

playbooks/collect-logs.yml
After Boaz confirm that logstash doesn't support .xz file, we
have to revert this commit
=> Revert commit 9d756b6f46

infrared/common/roles/cdn_registery/defaults/main.yml
repository information is a bit old and need an update for RHOSP13 and RHOSP14 which are already GA.
=> Update repository information for 13 and 14

plugins/tripleo-undercloud/init.yml, plugins/tripleo-undercloud/plugin.spec
This is in-line with the default from the tripleo-overcloud plugin.
=> [tripleo-undercloud] Set a default for overcloud_domain.
