redhat-openstack/infrared

- settings/installer/ospd/images/import.yml
- settings/product/rhos.yml
- settings/product/rhos/repo/common/common.yml
- settings/provisioner/virsh/image/rhel.yml
- settings/provisioner/virsh/topology/README.txt
- settings/provisioner/virsh/topology/all-in-one.yml
- settings/provisioner/virsh/topology/multi-node.yml
- settings/provisioner/virsh/topology/ospd_1cont_1comp.yml
- settings/provisioner/virsh/topology/ospd_1cont_1comp_1ceph.yml
- settings/provisioner/virsh/topology/ospd_3cont_1comp.yml
- settings/provisioner/virsh/topology/ospd_3cont_1comp_1ceph.yml
- settings/provisioner/virsh/topology/ospd_3cont_1comp_3ceph.yml
- settings/provisioner/virsh/topology/ospd_3cont_2comp.yml
- settings/provisioner/virsh/topology/ospd_3cont_2comp_1ceph.yml
- settings/provisioner/virsh/topology/ospd_3cont_2comp_3ceph.yml
> Remove old style lookup from settings

- cli/main.py
Cleanup and provision are mutually exclusive
fix #21
> Fix cleanup triggering

- cli/main.py
> Remove bad check at the end of execution

- cli/main.py
- settings/provisioner/virsh/virsh.spec
> Arguments are pathes to settings files

- cli/conf.py
- cli/execute.py
- cli/main.py
- cli/parse.py
- infrared.cfg.example
Modifies some files according the new structure.
Adds an example file of infrared.cfg
> Changes the infrared.cfg file structure

- cli/execute.py
- cli/main.py
- settings/provisioner/virsh/virsh.spec
The arguments are now passed directly to the playbook object.
> Removes the use in parser for playbook execution

- cli/conf.py
- cli/main.py
- cli/utils.py
- settings/provisioner/base.spec
- settings/provisioner/virsh/virsh.spec
> Obaranov spec manager

- cli/conf.py
- cli/main.py
- cli/utils.py
- settings/provisioner/base.spec
- settings/provisioner/virsh/virsh.spec
Initial implementation of the spec manager. 
Fix for #39 
@tkammer can you review and merge.
> Added Spec Manager to work with spec files

- settings/provisioner/virsh/topology/ospd_1cont_2comp_1ceph.yml
- settings/provisioner/virsh/topology/ospd_1cont_2comp_3ceph.yml
1 controller + 2 compute + 1 ceph
1 controller + 2 compute + 3 ceph
> Adding more topologies per request

- cli/main.py
> Fixes verbosity in ansible-playbook

- cli/conf.py
- cli/utils.py
Move constants tol utils
Fix #52
> Fix circular dependency between conf and utils

- cli/conf.py
- cli/utils.py
- tests/test_cwd/placeholder_double_injector.yml
- tests/test_cwd/placeholder_injector.yml
- tests/test_cwd/placeholder_overwriter.yml
- tests/test_cwd/utils.py
- tests/test_yaml.py
Adds a test exposing a bug in placeholder
> Recreate placeholder

- cli/conf.py
- cli/utils.py
- tests/test_cwd/placeholder_double_injector.yml
- tests/test_cwd/placeholder_injector.yml
- tests/test_cwd/placeholder_overwriter.yml
- tests/test_cwd/utils.py
- tests/test_yaml.py
An unexpected exception was raised when were more than one
'!placeholder' in the same file
resolves #55
> Fixes several placholders in the same file

- .travis.yml
> Reverts random order in unittests

- playbooks/installer/ospd/undercloud/pre.yml
Use yum module for update.
Reboot only if changed.
Relates to #60
> [OSPD] Reboot on update only

- cli/utils.py
> Fixes emtpy ref to a file in extra-vars ('-e @')

- cli/exceptions.py
- cli/execute.py
> [execute] Raise IRPlaybookFailedException

- cli/conf.py
- requirements.txt
> Preserves params order in help screen as in spec

- roles/ospd/overcloud/images/import/tasks/main.yml
> Replace wget with ansible get_url module

- cli/provision.py
- settings/provisioner/base.spec
> Issue #29 split debug from verbose

- README.rst
- cli/conf.py
- cli/exceptions.py
- cli/provision.py
- cli/utils.py
- provision.example.ini
- settings/provisioner/virsh/default.ini
- settings/provisioner/virsh/virsh.spec
* add additional argument and clg type
* update spec manager
> Add functionality to load args from ini file

- README.rst
- cli/conf.py
- cli/execute.py
- cli/provision.py
- cli/utils.py
- settings/provisioner/virsh/virsh.spec
Added env lookup for spec variables. Fixed args loading priority.
> [RHOSINFRA-14] Add environment lookup for spec arguments

- settings/provisioner/topology/ceph.yaml
- settings/provisioner/topology/compute.yaml
- settings/provisioner/topology/controller.yaml
- settings/provisioner/topology/undercloud.yaml
Fixes amount of memory on nodes per type
> [RHOSINFRA-74] Defines explicitly topology attributes

- .gitignore
- cli/execute.py
- cli/provision.py
- playbooks/provisioner/virsh/cleanup.yaml
- plugins/callbacks/human_log.py
- plugins/callbacks/timing.py
- requirements.txt
- roles/installer/ospd/overcloud/network/isolation/single-nic-vlans/tasks/main.yml
- roles/installer/ospd/overcloud/network/isolation/three-nics-vlans/tasks/main.yml
- roles/installer/ospd/overcloud/ssl/tasks/main.yml
- roles/installer/ospd/overcloud/storage/ceph/tasks/main.yml
- roles/installer/ospd/overcloud/storage/netapp/tasks/main.yml
- roles/provision/virthost/tasks/network.yml
- roles/provision/virthost/tasks/vms.yml
- roles/provision/virthost/templates/create_vms.sh.j2
- roles/provision/virthost/templates/network.xml.j2
- settings/provisioner/virsh/topology/network/default.yml
> RHOSINFRA-80 Execute Ansible 2

- cli/utils.py
- cli/yamls.py
- tests/test_yaml.py
@yfried-redhat, @aopincar please review
> [RHOSINFRA-122] Fix !random usage issue

- library/os_floating_ip.py
- requirements.txt
- roles/openstack/nova/tasks/setup_nodes.yml
Needed for os_floating_ip module.
> Add 'ipaddress' to requirements.txt

- library/os_floating_ip.py
Check that existing floater matches requirements
> Don't fail os_floating_ip on 2nd run

- library/os_floating_ip.py
- roles/openstack/nova/tasks/cleanup_nodes.yml
Pull latest module so it can purge floating ips.
Add option to delete floating ip by server and not by address.
> Cleanup floating ips

- cli/spec.py
@tkammer can you please review?
Usage example
```
ir-provisioner virsh --generate-conf-file=config.ini
ir-provisioner virsh -vvvv -i local-hosts --from-file=config.ini \
--host-address=rhos-qe-06.lab.eng.brq.redhat.com \
--image=rhel-7.2.yml \
-o provision.yml
ir-installer ospd --generate-conf-file=config.ini
ir-installer -vvvv -i hosts ospd --from-file=config.ini \
--product-version=8 \
--images-task=import \
--images-url=http://import-url \
--network-isolation=no-isolation.yml \
- e @provision.yml
```
> [RHOSINFRA-144] Config file generation improvements

- cli/conf.py
- tests/test_conf.py
> [RHOSINFRA-157] Fix auto cfg by adding provisioner and installer sections

- requirements.txt
- Ansible 2.0.2 is broken
- setuptools needs explicit version
> Fix stable requirments

- playbooks/installer/ospd/virthost.yml
- settings/product/rhos/version/9.0.yml
The task was failing if there's no authorized_keys file.
> Fix addition / creation of authorized_keys

- cli/utils.py
> [RHOSINFRA-44] Expands user in extra-vars ref ('@')

- settings/base.spec
- settings/installer/installer.spec
- settings/provisioner/provisioner.spec
- settings/tester/tester.spec
Creates specific SPEC file for each app.
Moves the inventory option from the base's spec to the app's spec.
Resolves RHOSINFRA-142
> [RHOSINFRA-142] Creates specific SPEC files with inventory to apps

- cli/utils.py
@yfried-redhat @arxcruz please review.
> [RHOSINFRA-176] job.archive's merging with -i flag

- infrared/common/roles/vbmc/tasks/main.yml
- plugins/tripleo-overcloud/install.yml
- plugins/tripleo-overcloud/plugin.spec
- plugins/tripleo-overcloud/tasks/network.yml
- plugins/tripleo-overcloud/templates/storage/internal.yml.j2
- plugins/tripleo-overcloud/templates/tripleo_roles/nodes.yaml.j2
- plugins/tripleo-overcloud/templates/tripleo_roles/tripleo_roles.sh.j2
- plugins/tripleo-overcloud/tripleo_roles.yml
Manually update the master branch because of sync issue with Gerrit & GitHub.
> Updates the master branch
